### ISSUE TITLE
Question about memory

### ISSUE THREAD

**Issue by rongmq8802** [tsunghan-mama/ReDAL#5]
Hello, first thank you for your excellent work. And I would like to ask you several questions.
1) When I run your program on S3DIS, after each active learning, the memory will increase greatly, resulting in cuda being out of memory. Is this the same when you are training?  I train the network on 4 1080Ti GPUs and set the batch size to 4.
2) And even if the second iteration can run successfully, the speed of a single epoch will be much slower. Is this normal?

**Comment by tuntun-sd** [comment]
Maybe you shoud better set the batch size to 2.  When I run the program on the SemanticKITTI dataset use the SPVCNN network,  I first set the batch size to 4 same with yours, I also met the same problem with you. Latter I set the batch size to 2, it succeed! My GPUs are also same with yours.

**Comment by tsunghan-wu** [comment]
Hi @rongmq8802, @tuntun-sd  

Thanks for asking a great question.
In fact, when I conducted the experiments, I also faced the same issue that training SemanticKITTI with SPVCNN requires a large amount of GPU memory. I found that "sparse convolution" in SPVCNN usually caused variated GPU memory utilization and the OOM problem. Since I only utilized SPVCNN in our experiment, you can check the original paper or raise issues on their repo if you are interested in some of the details.

To handle this issue, I trained the network with PyTorch Distributed Data Parallel. To be specific, I used 4 V100 GPUs (each contains 32 GB memory) and set 4 as the batch size for each GPU to conduct experiments on SemanticKITTI data. After that, I did not face the OOM and the speed issue. (Note: For the S3DIS dataset, I just use 1 V100 GPUs and set 4 as the batch size.)

Hope my reply address your points. If you have further problems or questions, feel free to ask me anytime!

Best,
Tsung-Han Wu

**Comment by rongmq8802** [comment]
Ok, thanks for your reply and excellent work again. Recently, I again trained the network on two new GPUs (V5000) with 24GB of memory, and it worked successfully when I set the batch size to 4. Besides, the results on S3DIS datasets are also very close to those reported in your paper.

**Comment by tsunghan-wu** [comment]
Very happy to hear that!

**Comment by nerminsamet** [comment]
Hello, thank you for your great work! I have a question regarding the training of SemanticKITTI with SPVCNN. In the training of ReDAL method, after the initial iteration, it takes 2 hours for a **single epoch** with 4 batch size on a single A100 (which has 80 GB GPU memory). Have you face the same problem? What could be the solution?

Thanks.

Log output:

20230222 21:44:44 INFO: **** EPOCH 000 ****
20230222 23:39:28 INFO: **** EPOCH 001 ****

**Comment by DpDark** [comment]
> Ok, thanks for your reply and excellent work again. Recently, I again trained the network on two new GPUs (V5000) with 24GB of memory, and it worked successfully when I set the batch size to 4. Besides, the results on S3DIS datasets are also very close to those reported in your paper.

Hi

How much MIoU you get for the S3DIS/SPVCNN? Using the ReDAL , I can only get 38.5% miou in 5% data , much lower than the performance in the paper. And, using the softmax_entropy I can get 38.6% miou in 5% data, even slight higher than the ReDAL!  What's more, for the random method I can get 35% miou in 5% data, higher than the performance presented in the paper. By the way, I using the two 3090(24GB) gpus for the experiment and the settings are default as same as the source code and paper.
